jdbc: 
  driverClassName: com.mysql.cj.jdbc.Driver
  #url: jdbc:mysql://localhost:3306/test?zeroDateTimeBehavior=convertToNull&amp;useUnicode=true&amp;characterEncoding=utf-8
  url: jdbc:mysql://localhost:3306/test?useSSL=false&serverTimezone=GMT%2B8
  username: root
  password: root
  
mybatis-plus: 
  type-aliases-package: com.yicj.study.shiro.entity
  mapper-locations: classpath*:com/yicj/study/shiro/xml/**Mapper.xml
  global-config:
    db-config:
      table-underline: true #驼峰下划线转换
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false